CREATE TABLE tb_client
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(100),
    email       VARCHAR(100) UNIQUE,
    api_key     VARCHAR(255) UNIQUE
);

CREATE TABLE tb_position
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_name VARCHAR(50),
    location      VARCHAR(50),
    url           VARCHAR(255) UNIQUE
);
